import type { Metadata } from "next"
import { Geist, Geist_Mono, Poppins } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css"

const poppins = Poppins({
subsets: ["latin"],
weight: ["400", "600", "700", "800"],
})

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
})

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
})

export const metadata: Metadata = {
title: "SoulTrack AI",
description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
     <html lang="en"> 
       <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
     </html>

      )
    }